
# build stage
FROM node:18.20.3-slim as build-stage
RUN yarn global add @quasar/cli
WORKDIR /app
COPY ./package.json .
COPY ./yarn.lock .
RUN yarn install
COPY . .
RUN quasar build -m pwa

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist/pwa /usr/share/nginx/html
COPY  ./nginx.prod.conf /etc/nginx/nginx.conf
EXPOSE 80
